FROM php:8.2-apache

ENV XDEBUG_VERSION=3.3.0

# Update and install dependencies
RUN apt-get update -yqq --fix-missing
RUN apt-get install -y --no-install-recommends \
    unzip \
    libzip-dev \
    libonig-dev \
    libxml2-dev \
    libjpeg-dev \
    libpng-dev \
    libfreetype6-dev\
    npm\
    git\
    wget

# Enable GD extension
RUN docker-php-ext-configure gd --with-jpeg=/usr/include/ --with-freetype=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- \
    &&  mv composer.phar /usr/local/bin/composer



# Install PHP extensions
RUN docker-php-ext-configure intl \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath zip intl

# Install Node.js and npm
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs
RUN apt-get install -y npm

# Add Node.js binary path to system's PATH
ENV PATH="/usr/local/bin/node:${PATH}"

RUN pecl install apcu && docker-php-ext-enable apcu\
    &&  pecl install xdebug-${XDEBUG_VERSION} \
    && docker-php-ext-enable xdebug

# Install Symfony CLI
RUN wget https://get.symfony.com/cli/installer -O - | bash \
    && mv /root/.symfony5/bin/symfony /usr/local/bin/symfony

RUN apt-get install -y vim

RUN a2enmod headers


#
RUN mkdir -p usr/local/etc/php/conf.d

WORKDIR /var/www
